version: "3.7"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ~/.docker/volumes/:/var/lib/postgresql/
    ports:
      - "5432:5432"
    networks:
      - default

  cache:
    image: redis:latest
    restart: always
    volumes:
      - ~/.docker/volumes/:/data
    ports:
      - "6379:6379"
    networks:
      - default